name: Bug Report
description: Report something that is broken on the website
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Shahada.org. Please fill out the details below.
  - type: input
    id: url
    attributes:
      label: Page URL
      description: Which page has the problem?
      placeholder: "e.g., https://shahada.org/en/"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: "e.g., The audio button does not play when clicked on iPhone Safari."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should happen?
      description: What did you expect to happen instead?
      placeholder: "e.g., The Shahada audio should play when the button is clicked."
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device and Browser
      description: What device and browser are you using?
      placeholder: "e.g., iPhone 15, Safari 17"
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot (optional)
      description: If possible, add a screenshot to help us understand the problem.
    validations:
      required: false
